route_names <- c(cat = 'One categorical variable', num = 'One numerical variable',
  group = 'A numerical variable across groups', cat2 = 'Two categorical variables', num2 = 'Two numerical variables')
route_prompts <- c(cat='How common is each category?', num='What is typical, and how much do values vary?',
  group='How do the distributions compare?',cat2='Which categories occur together?',num2='Do the measurements vary together?')
route_examples <- c(cat='For example: smoking categories',num='For example: hours of sleep',
  group='For example: wellbeing in two programmes',cat2='For example: smoking category by programme',num2='For example: sleep and wellbeing')
lesson <- function(title, text, question, takeaway) list(title=title,text=text,question=question,takeaway=takeaway)
lessons <- list(
 cat=list(
  lesson('What is a categorical variable?', c("Imagine asking every person in a study which way they usually travel to work. Their answers might be walking, cycling, bus or car. These are categories: they tell us which group a person belongs to, rather than how much of something the person has. A variable recorded this way is called categorical.","Blood group and a yes/no answer are other examples. Some categories have a natural order, such as low, medium and high. Here we asked fictional participants about smoking and recorded Never, Former or Current. Start by imagining putting each person into the box with their answer on it."), 'Are these category names, or amounts that can be meaningfully averaged?', 'A number can be a label: 1 and 2 might mean two groups, not numerical measurements.'),
  lesson('Count before calculating percentages', c("Once everyone is in a category, count the people in each box. That count is called its frequency. A percentage tells us how large that box is compared with a chosen total. For example, 14 out of 120 people is about 11.7%.","The total we divide by is called the denominator. If someone did not answer the question, we cannot put them in Never, Former or Current. We report them as missing and leave them out of the total used for the category percentages."), 'Out of which observations is this percentage calculated?', 'Always give the denominator. Missing does not mean Never, No or zero.'),
  lesson('Read the bar chart', c("A bar chart turns the counts into a picture: each labelled bar represents one category. A taller bar means more people, or a larger percentage, in that category. Switching between counts and percentages changes the scale but not who is in each category.","The gaps remind us that these are separate labels, not intervals along a measurement scale. Unless the categories have an order, moving the bars left or right would not change their meaning. Start the scale at zero so bar heights give a fair visual comparison."), 'Which category is most common? Is a difference large in counts, percentages, or both?', 'A bar chart describes this sample. It does not tell you why a category is more common.'),
  lesson('Write a useful description', c("Imagine describing the results to someone who cannot see the chart. “Some people smoked” tells them very little. Naming the category and giving the count out of the total lets them picture the size of the group.","Read the completed description below and find its numbers in the table. Include the missing count too: a reader should know whether everyone answered the question. At this stage we are describing our participants, not explaining why they belong to a category."), 'Could someone reading your sentence reconstruct its denominator?', 'You do not need a p-value to describe one categorical variable.'),
  lesson('Connect the result to R', c("Each button in the app has asked R to carry out a set of instructions. The script first reads the data file, then counts the people in each category, works out percentages and draws the bars. The output and the instructions belong together.","Expand the code box and look for one small task at a time. You do not need to understand every symbol immediately. If pipes or functions are unfamiliar, the New to R guide introduces them before data manipulation. The complete download lets you repeat the same work outside the app."), 'Which line counts the observations? Which line calculates the percentages?', 'You can copy the complete script or download it with the original data. No hidden app function is needed.')
 ),
 num=list(
  lesson('Identify a measurement', c("Imagine asking each participant how many hours they slept. An answer such as 6.5 hours describes an amount, so this is a numerical variable. Age, height and a laboratory measurement are other examples. The units tell us what the number means: 7 hours and 7 minutes are very different.","A participant ID may also contain numbers, but its job is to label a person. An average ID would not describe anyone meaningfully. Before calculating, say aloud what one number in your chosen column measures."), 'What do the values measure, and in which units?', 'Keep the units in your table, axis labels and explanation.'),
  lesson('Look at the shape first', c("Picture writing every participant’s sleep time on a card and lining the cards up from shortest to longest. Are most values gathered in the middle? Are there a few much larger values far away from the others? The histogram helps us see that pattern by putting nearby values into bins and counting them.","The boxplot underneath is another view of the same measurements. It marks the middle and the spread without showing every bar. Move the slider to change one person’s recorded value, then watch both pictures. We are deliberately changing one observation to see its influence, not discovering a real new participant."), 'Is the distribution roughly balanced, or does it have a long tail on one side?', 'Check unusual values against the source. A value is not an error just because it is unusual.'),
  lesson('Separate centre from spread', c("Two questions are different: what sleep time is typical, and how much do people differ? To find the mean, add the recorded hours and divide by the number of people. To find the median, order the values and look in the middle; if there are two middle values, average those two.","SD describes the spread of the individual sleep times around the mean. The box in a boxplot covers the middle half of the recorded values; its width along the measurement scale is the interquartile range, or IQR. Move one value far away and compare what happens to the mean, median and spread.","These summaries describe variation among people in this sample. In Estimation we ask a different question: how much might the sample mean change if another researcher studied different people? That is where standard error, or SE, is used."), 'Does an unusually large observation change the mean more than the median?', 'SD describes variability among observations. SE describes uncertainty in an estimate; it is not a substitute for SD.'),
  lesson('Understand right skew and logarithms', c("Now picture a measurement where most people have small values, but a few have very large values. The large values stretch the picture to the right. We call this a long right tail, or right skew. A logarithm changes the scale so that the large values are brought closer together.","Use the checkbox to compare the original marker measurements with their natural logarithms. The people have not changed; only the numbers used to represent their measurements have changed. Look for a shorter tail, while remembering that this will not always produce a balanced distribution.","The new axis is in log units, not the original measurement units. A natural logarithm requires positive values, so zeros and negatives need a different decision. Keep the original column so you can always return to it."), 'Has the long right tail shortened? What changed about the units?', 'Changing to logs changes the measurement scale. A mean on that new scale is not the mean of the original measurements.'),
  lesson('Report and reproduce', c("Imagine writing a short description for someone who has not seen the data. Say how many measurements were available, what a typical value looked like, how much people differed and how many values were missing.","If the picture is fairly balanced, the mean and SD may describe it well. If a long tail pulls the mean towards a few large values, the median and quartiles can help the reader picture where most people were. The table gives both. Choose your words using the graph as well as the numbers."), 'Which summary best describes your data, and what does it leave out?', 'Describe the distribution; do not let one summary replace looking at the plot.')
 ),
 group=list(
  lesson('Choose a measurement and a grouping variable', c("Imagine two rooms of participants: one room followed a walking programme and the other kept their usual routine. We record a wellbeing score for each person and want to see how the scores compare between the rooms.","Wellbeing score is the numerical measurement; programme is the categorical variable that tells us which room a person belongs to. Here each person contributes to one group. Measuring the same person before and after a programme would be a different, paired question."), 'Which variable is the measurement, and which separates the groups?', 'The numerical variable goes on the measurement axis. The categorical variable names the groups.'),
  lesson('Look inside each group', c("Start with the people inside each room, not just its average. In the figure, each dot is a person’s score. The boxes help us find the middle and the spread of each group. Both groups are drawn on the same measurement scale so we can compare them fairly.","A group can have a higher average yet overlap substantially with the other group. Two groups can also have similar averages but very different spreads. Look for both features. Dots are moved slightly sideways to reveal overlaps; the measured scores have not changed."), 'Do the groups differ mostly in centre, spread, or both?', 'Box width in this plot does not show sample size. Read the group counts in the table.'),
  lesson('Check the numbers behind the graph', c("A picture alone does not tell us how many people contributed. Check each group’s row in the table: how many scores are recorded, how many are missing and what are the mean and median? A summary based on three people needs a different reading from one based on three hundred.","SD shows variation in the original score units. Variance describes that same spread using squared units, so it is harder to picture directly. If someone’s programme label is missing, we cannot put them in either room; their exclusion is reported separately."), 'Does a group have few observations, more missing values, or unusually high spread?', 'Variance is another measure of spread, in squared units. SD is in the original units.'),
  lesson('Add a third variable only for a reason', c("Suppose you wonder whether the programme pattern looks similar among never-smokers, former smokers and current smokers. You could split each room into those smaller sets and compare the programmes within each smoking category.","In Analyse, the optional second grouping variable makes those separate panels. Only add it when it helps answer a question. Each split leaves fewer people per panel, so a dramatic-looking pattern may come from only a few observations. The tutorial’s main figure keeps the two programme groups together so the original comparison stays visible."), 'Does splitting the data answer your question, or just make the display busier?', 'A descriptive group difference alone does not establish a treatment effect or causation.'),
  lesson('Explain the pattern in words', c("Tell a reader which group tended to have higher scores, how much the scores varied and how many people were observed. Use the actual group names and score units, so the reader can picture who is being compared.","A difference in these sample summaries is a starting observation. Other differences between the people could help explain it. The Estimation section can add an interval for the difference between two population means; a descriptive figure alone does not establish a cause or a statistically significant effect."), 'Can you explain what the figure shows without making a causal claim?', 'Describe the observations first, then use Estimation to examine uncertainty about population differences.')
 ),
 cat2=list(
  lesson('Identify the two sets of categories', c("Imagine giving each participant two labels: their programme and their smoking category. A two-way table puts the programme labels down the rows and smoking labels across the columns. Each person belongs in the cell where their two labels meet.","Find the Programme row you want, then the smoking column. The number at their intersection counts people with both labels. The totals let you check how many people are in each row, each column and the whole table before any percentages are calculated."), 'What question do the rows answer? What question do the columns answer?', 'An empty combination means a count of zero. A missing value is a separate issue.'),
  lesson('Choose the denominator deliberately', c("The same table can answer different questions. “Among people in the walking programme, how many are current smokers?” starts with one programme row. “Among current smokers, how many are in the walking programme?” starts with one smoking column.","For the first question, divide by the row total. For the second, divide by the column total. If you divide by everyone in the table, you are asking how common that combination is in the whole sample. Change the denominator and say the question aloud each time."), 'Are you asking “within this programme” or “within this smoking category”?', 'The same counts give different percentages when the denominator changes. Neither is automatically wrong.'),
  lesson('Connect the bars to the table', c("The bars redraw the table as a picture. The programme names identify the groups of bars and the colours identify smoking categories. Each bar belongs to one cell in the table, so you can trace its height back to that cell’s percentage.","Changing the denominator changes the question and therefore the bar heights, even though the counts stay the same. With row percentages, the smoking-category bars within one programme add to 100%. With column percentages, bars of one smoking colour add to 100% across programmes."), 'Which set of bars should add to 100% in this view?', 'Always read the vertical-axis label before interpreting the height of a bar.'),
  lesson('Notice missingness and sparse combinations', c("Imagine a cell containing one person. If that person is the only person in their row, the row percentage is 100%. That sounds large, but it rests on a very small amount of information. Always return to the count table before interpreting an impressive percentage.","We need both labels to place someone in a cell. Someone with a missing smoking category or programme is excluded from this two-variable table, and that count is reported. Zero in a cell means nobody with both recorded labels had that combination; it does not mean their answer was missing."), 'Is an apparent difference supported by many observations or very few?', 'Small denominators can make percentages look dramatic.'),
  lesson('Describe a comparison clearly', c("Describe the comparison in the same order as the question. For example, start “Within the walking programme…” when you use row percentages. Give the count and denominator along with the percentage so the reader can picture the people behind it.","Look at the completed description and the chosen denominator together. Swapping the row and column question changes what the percentage means. These are descriptions of the sample; later analyses can estimate differences or test particular questions."), 'Would swapping the row and column roles answer a different question?', 'These are descriptive comparisons. Formal tests will be added in the next release stages.')
 ),
 num2=list(
  lesson('Start with two measurements on each observation', c("Imagine placing one dot on a sheet for each participant. Move right according to their hours of sleep and up according to their wellbeing score. The dot shows that person’s two measurements together. A cloud of these dots is called a scatterplot.","A participant needs both measurements to appear. If either is missing, we cannot place their dot. Check the units on the two axes and the number of complete pairs before interpreting the pattern."), 'What does one point represent? What are the units of each axis?', 'Put the explanatory measurement on the horizontal axis when that interpretation makes sense; this does not establish causality.'),
  lesson('Describe the shape of the relationship', c("Look at the cloud before calculating a number. If dots tend to rise as you move right, people with more sleep tend to have higher wellbeing scores: a positive association. If they tend to fall, the association is negative.","Now ask whether the pattern looks roughly straight or curved. Are there separate clusters, or one unusual person far from everyone else? A single straight-line summary can miss a clear curved pattern, so the picture remains part of the explanation."), 'Is the pattern roughly straight, curved, or not clearly patterned?', 'Always look at the scatterplot before interpreting a correlation.'),
  lesson('Choose Pearson or Spearman thoughtfully', c("Pearson correlation summarises how closely the dots follow a straight-line pattern, using the actual measurements. Spearman correlation instead asks whether people who rank higher on one measurement also tend to rank higher on the other.","For either, a value near +1 means a strong increasing pattern of the relevant kind and a value near −1 means a strong decreasing pattern. A value near 0 means little association of that kind; it does not rule out a curved relationship. Change the selector and compare the number with the same cloud of dots."), 'Does the question concern a roughly straight relationship, or a consistent ordering?', 'A near-zero correlation can miss a curved pattern. If everyone has exactly the same value for a variable, its correlation cannot be calculated.'),
  lesson('Look within groups when it helps', c("Suppose participants belong to different programmes. A pattern in the combined cloud could partly reflect the differences between programmes. Looking separately within each programme helps you see whether people with more sleep also tend to have higher scores within that group.","Analyse offers an optional grouping variable for separate panels. This is a way to inspect the pattern, not a method that adjusts for every other difference between people. The tutorial’s figure continues to show the overall sample for reference."), 'Is the same pattern visible within each group?', 'Correlation does not prove that changing one measurement causes the other to change.'),
  lesson('Report the coefficient with context', c("Imagine explaining the relationship to someone without showing them the coefficient first. Say what one dot represents, whether the cloud rises or falls, and whether it looks straight, curved or scattered. Then give Pearson or Spearman by name and the number of complete pairs.","A relationship between sleep and wellbeing does not show that changing sleep would change wellbeing. Other factors may affect both, and the direction of explanation may be uncertain. Use the plot and the completed description together rather than treating the coefficient as the whole result."), 'Can someone understand the relationship from your plot and sentence together?', 'The complete R script reproduces the scatterplot, the selected coefficient and any grouping.')
 ))

prep_help <- list(
 type=c('Numbers can be labels', 'Choose Categorical for group codes, Numerical for measurements, or Text / ID for identifiers. Changing the type does not create information. If a text value cannot safely become a number, the app stops and explains why.'),
 filter=c('Keep observations for a clear reason', 'A filter keeps rows that meet a condition. Add several conditions, then choose ALL (AND) or ANY (OR). Missing values do not pass an ordinary comparison; use “is missing” explicitly when needed. Preview the row count before applying. Sequential applied filters are AND across steps.'),
 derive=c('Create a new variable and preserve the original', 'Use a new, meaningful name. Available operations are natural log, multiplying or adding a constant, difference, ratio, a threshold-based category, or replacing a category label. Think about units and the question before changing the data. Recode one label at a time; further steps can build on a previous derived column.')
)


# Completed tutorial descriptions use the same result table as the figure.
tutorial_description <- function(t) {
  a <- t$result$table; d <- apply_steps(t$raw,t$steps); s <- t$spec
  f <- function(x,digits=1) formatC(x,format='f',digits=digits)
  if(s$route=='cat') {
    current<-a[a$category=='Current',]; total<-sum(a$n); missing<-sum(is.na(d[[s$x]]))
    return(paste0('Among ',total,' participants with recorded smoking status, ',current$n,
      ' were current smokers (',f(current$percent),'%). Smoking status was missing for ',missing,' participants.'))
  }
  if(s$route=='num') {
    label<-switch(s$x,sleep_hours='Hours of sleep',marker='The marker measurement',log_marker='The natural log of the marker measurement',s$x)
    units<-if(s$x=='sleep_hours')' hours' else if(s$x=='log_marker')' log units' else ' units'
    return(c(paste0(label,' was recorded for ',a$n,' participants, with ',a$missing,' missing values. The mean was ',f(a$mean),units,' (SD ',f(a$sd),').'),
      paste0('The median was ',f(a$median),units,'. The middle half of observed values lay between ',f(a$q1),' and ',f(a$q3),units,' (IQR ',f(a$IQR),').')))
  }
  if(s$route=='group') {
    sentences<-vapply(seq_len(nrow(a)),function(i)paste0('In the ',a$group[i],' group, ',a$n[i],
      ' participants had recorded wellbeing scores (',a$missing[i],' missing). The mean was ',f(a$mean[i]),
      ' points (SD ',f(a$sd[i]),'); the median was ',f(a$median[i]),' points.'),character(1))
    return(c(sentences,'These summaries describe the participants in this example; they do not establish that the programme caused a difference.'))
  }
  if(s$route=='cat2') {
    total<-sum(a$n); missing<-nrow(d)-total
    current<-a[a$column_group=='Current',]
    if(s$denom=='row') lines<-vapply(seq_len(nrow(current)),function(i){
      n<-sum(a$n[a$row_group==current$row_group[i]])
      paste0('Within the ',current$row_group[i],' group, ',current$n[i],' of ',n,' participants were current smokers (',f(current$percent[i]),'%).')
    },character(1)) else if(s$denom=='column') lines<-vapply(seq_len(nrow(current)),function(i)
      paste0('Among the ',sum(current$n),' current smokers, ',current$n[i],' were in the ',current$row_group[i],' group (',f(current$percent[i]),'%).'),character(1)) else lines<-vapply(seq_len(nrow(current)),function(i)
      paste0('Of all ',total,' participants with both variables recorded, ',current$n[i],' were current smokers in the ',current$row_group[i],' group (',f(current$percent[i]),'%).'),character(1))
    return(c(lines,paste0(missing,' participants were excluded because at least one of the two category values was missing.')))
  }
  coefficient<-a$correlation[1]
  direction<-if(is.na(coefficient))'could not be calculated' else if(coefficient>0)'was positive: participants with more sleep tended to have higher wellbeing scores' else if(coefficient<0)'was negative: participants with more sleep tended to have lower wellbeing scores' else 'was zero in this sample'
  c(paste0('There were ',a$n[1],' participants with both sleep and wellbeing recorded; ',nrow(d)-a$n[1],
    ' were excluded because one or both measurements were missing. The ',tools::toTitleCase(s$cor),
    ' correlation was ',if(is.na(coefficient))'unavailable' else f(coefficient,2),'.'),
    paste0('The association ',direction,'. This does not show that changing sleep would cause wellbeing to change.'))
}

# A short introduction beside every teaching figure: what it shows and what to look for.
descriptive_context <- function(route,i) {
 contexts<-list(
 cat=c('We recorded the smoking category of 120 fictional participants. Each bar gathers people with the same label. Look for the largest and smallest groups.',
 'The table counts each category before dividing by the recorded total. Switch between count and percentage and check that the most common category stays the same.',
 'Trace one bar back to its row in the table. The height should match the chosen count or percentage. Say which category that bar describes.',
 'Use the actual table to check each number in the completed description on the left. The denominator tells you whose answers are included.',
 'This is the same example as before. Expand the code to connect the import, counting and plotting instructions to the output you can see.'),
 num=c('These are fictional sleep times. The histogram groups people with similar hours; the boxplot summarises the same measurements. First identify what is measured and the units.',
 'The slider deliberately increases one person’s sleep time. Move it slowly and watch the right-hand end of the histogram and the boxplot. Ask what changed and what stayed similar.',
 'Use the slider again, but now compare the mean and median in the table as well as the figures. One large value can pull the mean while leaving the middle person almost unchanged.',
 'Here we switch to a fictional positive marker measurement with a long right tail. The checkbox changes between its original and log values. Compare the shape and read the changed axis label.',
 'Read the completed description against the table and the figure. Include a typical value, a measure of spread, units and the observed and missing counts.'),
 group=c('The fictional participants belong to two programmes. Each point is a wellbeing score. Compare the middle and spread within each group before comparing their averages.',
 'The same scores are shown on a shared scale. Find where the two sets overlap and whether one set is more spread out. The boxes do not show how many people are in each group.',
 'Read one group’s count, mean and SD, then find that group in the picture. Repeat for the other group. Missing counts explain whose scores are absent.',
 'This picture keeps the overall programme comparison visible. In Analyse you can choose a second grouping variable to ask whether this pattern also appears within smaller sets of people.',
 'The completed sentences use the displayed values. Match their claims about group size, averages and variation to the table and points.'),
 cat2=c('Each cell counts people with one programme label and one smoking label. Read the row and column names and their totals before choosing any percentage.',
 'Use the dropdown only after looking at the count table. First ask a question beginning “Within this programme…”, then one beginning “Among current smokers…”. Watch how the percentages change.',
 'Pick a cell in the table and find its matching bar using the programme label and smoking colour. Change the denominator and check which collection of bars now adds to 100%.',
 'Look for small cell counts before interpreting large percentages. The same count table remains visible so you can keep the number of people in mind.',
 'Read the completed sentences using the currently selected denominator. Switching the denominator changes the sentence’s question as well as its numbers.'),
 num2=c('Each dot is a fictional participant with both sleep and wellbeing recorded. Read the two axes, then pick a dot and describe what its position means.',
 'Scan the cloud from left to right. Decide whether it tends to rise, fall or bend, and notice any dots that do not follow the general pattern.',
 'The points stay the same when you switch Pearson and Spearman. You are changing how their association is summarised, not changing the people or their measurements.',
 'This figure shows everyone together. Compare it with separate programme panels in Analyse if you want to see whether the overall pattern also holds inside each group.',
 'Match the completed description to the cloud. The coefficient helps summarise what you see; the shape and the number of complete pairs still matter.')
 )
 contexts[[route]][i]
}
