# Explain the study first; introduce a statistical name only after the idea.
single_est_lesson <- function(kind, i) {
  mean<-kind=='mean'
  titles<-c('Who are we trying to learn about?','What if another researcher repeated our study?','People vary; study results vary too','What does a confidence interval tell us?','What changes when we include more people?','Put the result into words')
  texts<-list(
    if(mean)c('Suppose we want to know how many hours adults in a particular community usually sleep. We cannot ask every adult, so we invite some of them to join our study. The people who take part are our sample. The larger group we want to learn about is our population.',
      'We add the recorded hours and divide by the number of people with a recorded value. This gives the sample mean. It describes our participants, and we use it as our best estimate of the population mean. We usually do not know that population mean.') else c('Suppose we want to know what proportion of adults in a community are aged 40 or older. We study a sample of adults and count how many meet that description. Here “event” simply means the category we choose to count; it does not have to mean an illness.',
      'If 40 of 100 people are aged 40 or older, the sample proportion is 40/100 = 0.40, or 40%. We use the percentage in our sample to estimate the percentage in the larger population. The example on the right uses fictional participants, not your uploaded data.'),
    if(mean)c('Our study gives us just one of many samples that could have been selected. Imagine another researcher repeating the same study in the same community, using the same way of choosing participants. They would probably include different people. Some may sleep more and some less, so their sample mean may differ from ours.',
      'Now imagine many researchers each doing that study. Their sample means would vary from study to study, even though they are all trying to learn about the same population, whose mean is fixed for this example. In a real study, that fixed population mean is usually unknown. This is what we mean by sampling variation.') else c('Imagine another researcher asking a different sample of adults from the same community. By chance, their sample might contain a few more people aged 40 or older, or a few fewer. Their sample percentage could therefore differ from ours.',
      'Now picture 100 researchers, each selecting their own sample in the same way. We would get 100 percentages. The percentage in the population has not changed in this example; it is the people selected into each sample that have changed.'),
    if(mean)c('First picture the people in one study. One person may sleep 5 hours, another 7 hours and another 9 hours. Standard deviation, or SD, describes how spread out these individual sleep times are.',
      'Now picture the average reported by each of many studies. Standard error, or SE, describes how the sample mean varies from sample to sample. Averaging brings high and low values together, so these means generally vary less than the individual people’s measurements. A study with more independent participants usually has a steadier mean.',
      'We normally have only one study. We use the spread of its individual values and its number of participants to estimate the SE. In this computer example we can repeat the study, so we can actually see the spread of the sample means.') else c('Within one study, each person either is or is not in the category we are counting. Our study turns those individual answers into one percentage.',
      'If we repeated the study with different people, we would get slightly different percentages. Standard error, or SE, describes how much that sample percentage varies from sample to sample. It is measured in percentage points here. It is not an error in a person’s answer or a percentage of mistakes.'),
    c('Our sample gives one estimate, but another sample would probably give a slightly different one. A confidence interval adds a range around the estimate to show the uncertainty that comes from studying a sample. Read it as a range of population values reasonably compatible with the data and the method’s assumptions.',
      'To understand “95%”, imagine repeating the entire study many times and making an interval each time. A method with 95% coverage would include the fixed population value in about 95 out of every 100 such intervals in the long run. The intervals move because the samples change. The population value does not move.',
      'The computer can show which intervals miss because we have chosen the population value ourselves. In real research we usually do not know it, so we cannot label our one interval as a hit or a miss. A 95% interval does not contain 95% of the people, and this interpretation does not assign a 95% probability to the fixed value being inside the interval we obtained.'),
    c(if(mean)'Think of asking 10 people about their sleep, then asking 100 people. With only 10, including just one unusually short or long sleeper may noticeably change the mean. With more independent people, any one person usually has less influence, so results from repeated studies tend to be closer together.'else'Think of sampling 10 adults, then 100 adults. In the smaller study, one extra person aged 40 or older changes the percentage by 10 percentage points. In the larger study, one person changes it by only 1 percentage point. Repeated studies with more independent people usually give percentages closer together.',
      'First increase the number of people in each study and look for less spread between the estimates and shorter intervals. Then keep that number fixed and increase the confidence level. To be more confident that our method catches the population value, we use a wider interval.',
      'More people do not fix the wrong kind of sample. Asking 1,000 people from one night-shift workplace may still tell us little about all adults in the community. Nor should several records from one person be treated as several independent people.'),
    c('Imagine explaining your study to someone who has not seen the table. Start with whom you studied and what you measured or counted. Give the estimate, its units, the confidence interval and the number of people whose values were available. Mention how many were missing.',
      'The sentences on the right use the actual numbers in the worked example. Match each number to the table. If you show separate groups, each interval describes that group’s population mean or proportion. To estimate the difference directly, choose the two-group comparison on the Estimation main page.')
  )
  list(title=titles[i],text=texts[[i]])
}
comparison_lesson_count <- function(kind) if(kind=='mean')6L else 8L
comparison_lesson <- function(kind,i) {
 if(kind=='mean'){
  titles<-c('Picture two groups of different people','Calculate each mean before comparing them','Subtract in a clearly stated order','Why does a difference need an interval?','What does zero in the interval mean?','Read the whole result, then reproduce it')
  texts<-list(
   c('Suppose a researcher studies sleep in people following a walking programme and in people keeping their usual routine. Each person belongs to only one group and contributes one sleep measurement. We want to compare the population averages, not decide which individual slept longest.', 'This route is for different, independent people in the two groups. A before-and-after measurement on the same person is a different, paired question.'),
   c('Start by looking at the people in each group. Calculate an average for each group, but also look at the spread of individual sleep times and the number of people observed. Two averages alone can hide very different sets of people.', 'The boxes and points show the measurements in this fictional study. A point is a person, not a group mean. Missing measurements do not contribute to either mean, and the table reports them.'),
   c('To describe how far apart the averages are, subtract one mean from the other. We choose the usual-routine group as our reference. Here the calculation is: walking-programme mean minus usual-routine mean.', 'A positive answer means more sleep on average in the walking group; a negative answer means less. The difference stays in hours. If we reverse the groups, the number changes sign but describes the same comparison.'),
   c('Imagine another researcher repeating this two-group study with different people in both groups. Both sample means would move a little, so their difference would move too. Our observed difference is therefore an estimate, rather than the exact population difference.', 'The interval around the difference allows for uncertainty in both means. We use a Welch interval, which allows the amount of individual variation to differ between the two groups. We still need independent observations and should inspect skew and unusual measurements, especially in small groups.'),
   c('A difference of zero means the two population means are equal. Look at the line for the confidence interval and the dashed line at zero. If the interval crosses or touches zero, equal population means are still compatible with these data and the method’s assumptions.', 'This does not show that the means are the same. The interval also contains other possible differences. If it is wide, it may include differences large enough to matter. If zero is outside, consider the direction and size of the remaining differences as well as their uncertainty.'),
   c('Report the mean in each group, then the difference in the stated order, its units and its confidence interval. Use the interval for the difference itself; do not decide this by whether the two separate group intervals overlap.', 'The larger-study option repeats the same fictional sleep patterns more times. It holds the observed means fixed so that you can see the effect of sample size on interval width. This is a teaching construction, not newly collected evidence. Even a precise difference would not, by itself, prove that the programme caused it.')
  )
  contexts<-c('We create two fictional groups. Begin with the observed people and the separate group summaries. Notice whether one group tends to have longer sleep times.',
   'Read the two rows of the summary table and compare them with the individual points. Check the sample sizes as well as the means.',
   'Below the group summaries, follow the numerical subtraction. We keep the order visible so that the sign of the result has a meaning.',
   'The dot is the observed difference. The horizontal line is its confidence interval. It describes uncertainty about the difference, not the spread of individual sleep times.',
   'Compare the smaller and larger study. The group means stay the same by construction; the interval changes because there are more observations. Ask whether zero remains inside.',
   'Read the completed description, then expand the R code. The download includes these exact fictional data and the full calculation.')
 }else{
  titles<-c('Define the outcome and the two groups','Count people before calculating percentages','Subtract percentages: the risk difference','Divide risks: the risk ratio','What do odds mean?','Compare odds: the odds ratio','Find the no-difference value in an interval','Report the comparison in the study’s context')
  texts<-list(
   c('Imagine following two groups of people for the same one-month period and recording whether each person reports a symptom. Each person is counted once, as symptom or no symptom. We compare a programme group with a usual-routine group.', 'In this example the proportion developing a symptom over that month is a risk. If we instead recorded who had a condition on one day, we would call the proportion a prevalence. The study question determines the words we use.'),
   c('Start with the two-way count table. Each row is a group. The Event column counts people with the symptom and the Other outcome column counts people without it. Add them to get the denominator for that row.', 'Divide the event count by that group’s total. For example, 50 events among 100 people means a risk of 50%. Do this separately for both groups before comparing them. Keep the counts visible: 5 of 10 and 500 of 1,000 are both 50%, but do not carry the same amount of information.'),
   c('Subtract the reference-group percentage from the comparison-group percentage. With 50% in the programme group and 40% in usual routine, the risk difference is 10 percentage points. That is 10 more events per 100 people in the programme group in this sample.', '“10 percentage points higher” is different from “10% higher”. A difference is an absolute comparison on the percentage scale. It does not tell us why the groups differ.'),
   c('Now ask a different question: how many times as large is one risk as the other? Divide the programme risk by the usual-routine risk. With risks of 50% and 40%, the risk ratio is 50/40 = 1.25.', 'This is 1.25 times the risk, or 25% higher risk relative to the reference. It is still the same 10-per-100 absolute difference. A ratio of 1 means equal risks; below 1 means a lower risk in the comparison group. Always say which event, time period and reference group you mean.'),
   c('Risk compares events with everyone in the group. Odds compare events with non-events. Picture a group of 100 people: if 40 have the symptom and 60 do not, the risk is 40/100 = 0.40, while the odds are 40/60, about 0.67.', 'These describe the same group using different denominators. Odds are not percentages. In a group with 50 events and 50 non-events, the odds are 50/50 = 1, meaning one event for every non-event.'),
   c('Calculate the odds in each group, then divide the programme odds by the reference odds. With 50 events and 50 non-events versus 40 events and 60 non-events, the odds ratio is (50/50)/(40/60) = 1.50.', 'That means 1.50 times the odds, not 1.50 times the risk. In this same example the risk ratio is 1.25. When outcomes are common, an odds ratio above 1 can look further from 1 than the risk ratio. Keep the wording “odds” when reporting an odds ratio.'),
   c('Imagine repeating the study with different people. The event counts and percentages would change, so the differences and ratios would change too. Each interval shows the sampling uncertainty for its particular comparison.', 'For a difference, the no-difference value is 0. For either ratio, it is 1, because dividing equal values gives 1. If the interval includes that value, equal population risks or odds remain compatible with the data and assumptions. This does not prove equality. Read how wide the interval is and which larger or smaller effects it also includes.'),
   c('Begin with the event definition, follow-up period, reference group and the counts and percentages. Then name the comparison you are reporting, its estimate and confidence interval. The completed description below keeps the direction explicit.', 'Imagine deciding to study exactly two people: one who is left-handed and one who is right-handed. In your sample, 1 out of 2 people is left-handed, so the sample prevalence is 50%. You can calculate that perfectly well. But it does not tell us that half the population is left-handed: you deliberately chose the sample to contain one of each. If you chose one left-handed and nine right-handed people instead, the sample prevalence would be 10%, even though nothing in the population had changed.',
    'A case-control study works on the same principle: researchers select people who have the outcome (cases) and people who do not (controls). We can calculate the outcome percentages within the selected groups, subtract them or divide them to obtain a difference or ratio. Those calculations are possible, but the resulting numbers depend on how cases and controls were selected. They do not directly estimate population risks, a population risk difference or a population risk ratio.',
    'That is why this app does not present those differences and ratios as population risk estimates for a case-control study. An odds ratio can still be informative when cases and controls have been selected appropriately. In a one-time survey, use prevalence language. Always explain how people entered the study, and remember that an unadjusted comparison alone does not establish cause and effect.')
  )
  contexts<-c('The fictional event is a symptom during one month. The two sliders set how many out of each 100 people have that symptom. We use these to construct the count table.',
   'Look at one row at a time: count the events, add both outcome columns, then divide. The same people will be used for every comparison that follows.',
   'The worked subtraction below uses the current percentages. Change one slider and watch how many more or fewer events per 100 it represents.',
   'The worked division uses the same percentages as the previous step. Compare its answer with the absolute difference to see why both can be useful.',
   'The worked lines below change the denominator from everyone to non-events. Compare risk and odds within each group before comparing the groups.',
   'The worked odds ratio uses the same four cells. Compare it with the risk ratio; do not read one as the other.',
   'Use the figure selector to switch between the difference and the two ratios. Look for 0 on the difference plot and 1 on a ratio plot. The larger-study option keeps the percentages fixed while increasing the counts.',
   'The table and sentences use your current example settings. Expand the code or download the script and these data to reproduce them outside the app.')
 }
 list(title=titles[i],text=texts[[i]],context=contexts[i])
}
