h_example <- function(k) {
 before<-c(6.1,7.2,6.8,5.9,7.4,6.5,7.0,6.2,7.8,6.7,7.1,6.4)
 after<-before+c(.4,.2,-.1,.8,.1,.5,-.2,.7,.3,.6,-.1,.4)
 d<-switch(k,one=data.frame(sleep_hours=before),paired=data.frame(before=before,after=after),
 two=data.frame(sleep_hours=c(before,after),programme=rep(c('Usual routine','Walking programme'),each=12)),
 many=data.frame(sleep_hours=c(before,after,before+c(.9,.6,.5,.8,.3,.7,.4,.9,.6,.8,.2,.5)),programme=rep(c('Usual routine','Walking programme','Sleep workshop'),each=12)),
 binary=data.frame(response=c(rep('Yes',14),rep('No',26))),
 categorical=data.frame(programme=rep(c('Usual routine','Walking programme'),each=100),response=c(rep('Yes',40),rep('No',60),rep('Yes',60),rep('No',40))),
 paired_binary=data.frame(before=c(rep('No',30),rep('No',12),rep('Yes',3),rep('Yes',15)),after=c(rep('No',30),rep('Yes',12),rep('No',3),rep('Yes',15))))
 method<-switch(k,one='t_one',paired='t_paired',two='welch',many='anova',binary='binomial',categorical='chi',paired_binary='mcnemar_exact')
 s<-list(route=k,x=names(d)[1],y=if(ncol(d)>1)names(d)[2]else'',reference=if(k%in%c('two','many'))'Usual routine'else'',event='Yes',null=if(k=='one')7 else if(k=='binary').5 else 0,log=FALSE,method=method,alternative='two.sided',alpha=.05,posthoc=FALSE)
 if(k=='categorical'){s$x<-'programme';s$y<-'response'}
 list(raw=d,spec=s,meta=list(kind='csv',name=paste0('hypothesis_',k,'_example.csv'),delim=',',decimal='.',encoding='UTF-8',na=c('','NA')))
}
h_method_lesson <- function(m) {
 switch(m,
 t_one=c('Imagine checking whether adults in a population sleep an average of 7 hours. Your sample will almost never average exactly 7, even if that is the population mean. A one-sample t-test asks whether the observed difference is large compared with the uncertainty in the sample mean.', 'Use independent observations. With a small sample, the population distribution should be reasonably close to normal, without severe skew or extreme values. The confidence interval helps show which population means are compatible with the observations.'),
 t_paired=c('Imagine measuring sleep before and after a programme in the same people. Someone who starts with short sleep may still have short sleep afterwards. The two measurements belong together, so keep each person’s measurements on the same row.', 'Subtract before from after for every complete pair. The paired t-test asks whether the average change in the population differs from the stated no-change value, usually 0. Inspect the distribution of these changes. The separate before and after distributions do not both need to be normal. There is no equal-variance decision between before and after.'),
 welch=c('Imagine comparing sleep in a walking group and a usual-routine group made up of different people. First compare the two means. Then ask whether that difference is large compared with its sampling uncertainty.', 'Welch’s t-test allows the population variances to differ. It also works when variances happen to be equal, and is a useful choice when you are unsure. Independence and an appropriate distributional approximation still matter. A Welch test does not solve dependence, extreme outliers or strong skew in a small sample.'),
 pooled=c('The equal-variance t-test combines information about spread from the two groups into one estimate. This is sensible when the populations have roughly the same variance and the observations are independent.', 'Compare the observed variances, sample sizes and boxplots. There is no universal sample-variance ratio that proves the assumption. If equality is doubtful, Welch’s t-test is usually the more defensible choice. Both versions test a difference in population means.'),
 anova=c('Imagine comparing usual routine, walking and a sleep workshop. Running a separate unadjusted t-test for every pair creates more chances to obtain a small p-value just by sampling variation.', 'One-way ANOVA begins with one overall question: are all population means equal? It compares separation of group means with variation within groups. It assumes independent observations, roughly normal errors within groups and approximately equal population variances. A small overall p-value says that at least one mean differs; it does not identify which one.', 'After inspecting the overall result, Tukey follow-up comparisons examine all pairs while accounting for the number of comparisons. Their intervals and p-values are adjusted together. Avoid choosing only the pairs whose unadjusted p-values look promising.'),
 welch_anova=c('The groups may have noticeably different spreads. Welch’s one-way ANOVA compares their population means while allowing unequal variances. It is the several-group counterpart of Welch’s t-test.', 'Observations must still be independent and the within-group distributions need a suitable normal approximation. The overall test does not identify a particular pair. This app offers pairwise Welch t-tests with Holm adjustment as follow-up comparisons; these are labelled explicitly rather than called Tukey tests.'),
 signed=c('Imagine lining up each person’s change from smallest to largest. The signed-rank test uses both the direction of a change and the rank of its distance from the stated centre. Larger absolute changes get higher ranks.', 'This avoids a normal-distribution assumption, but still requires a roughly symmetric distribution of deviations around a common centre. Picture a shape whose left and right sides are roughly balanced. If that is implausible, a sign test may better match the question.', 'The signed-rank test is not generally a test of an arithmetic mean. For paired data it uses after-minus-before changes. Exact zeros do not contribute to signed ranks; ties or larger samples lead this app to use a normal approximation, which may be poor with very small tied samples.'),
 sign=c('Imagine counting only the arrows: how many observations are above the stated value, and how many are below it? For paired data, how many people increased and how many decreased? The sign test ignores how large the changes are.', 'Under the null hypothesis, either direction is equally likely among non-zero deviations. An exact binomial calculation tests that balance. It does not need symmetric change sizes, but it throws away information about magnitude.', 'Exact ties are omitted and reported. For a continuous outcome, the test can be interpreted as a test of the population median or median change. With many ties, describe the conditional comparison among non-ties carefully.'),
 rank=c('Imagine mixing the two independent groups together and arranging all measurements from smallest to largest. Give each measurement a rank, then look at which group tends to receive the higher ranks. This is the Wilcoxon rank-sum test, also called the Mann–Whitney test.', 'The test does not require a normal distribution. It still needs independent observations and comparable measurements. It compares distributions through ranks; it is not a replacement test of the two arithmetic means.', 'If the distributions have similar shapes and differ mainly in location, a location or median interpretation can be useful. If the shapes and spreads differ, do not describe every small p-value as proof that the medians differ. Show the plots and describe the pattern.'),
 kruskal=c('With three or more independent groups, pool and rank all the measurements. Kruskal–Wallis asks whether the group rank patterns are more different than would be expected under its null model.', 'It does not require normality, but observations must be independent. It compares distributions through ranks, not arithmetic means. A median-only interpretation needs comparable distribution shapes.', 'The overall p-value does not identify which groups differ. The optional follow-up here uses pairwise Wilcoxon rank-sum tests with Holm-adjusted p-values. Inspect the group patterns as well as these comparisons.'),
 binomial=c('Suppose you ask 40 people a Yes/No question and 14 answer Yes. The observed proportion is 14/40 = 35%. You want to compare the population proportion with a stated value, for example 50%.', 'Even if the population proportion were 50%, samples would not always contain exactly 20 Yes answers. The exact binomial test adds up the probabilities of outcomes as extreme as, or more extreme than, the observed count under that null model.', 'People must contribute independent binary observations with a common event probability under the model. The test also works when nobody, or everybody, has the event. Exact refers to the binomial calculation; it does not repair biased sampling or dependence.'),
 prop=c('A one-sample proportion test compares the observed event count with the count expected under a stated population proportion. For example, with 40 people and a null proportion of 50%, the expected counts are 20 events and 20 non-events.', 'This test uses a large-sample chi-squared approximation. In this teaching route, both expected counts must be at least 5 before it is offered. The exact binomial option is also available. This app uses no continuity correction and records that setting in the code.'),
 chi=c('Start with the observed two-way table. Suppose the row labels are programmes and the columns are Yes and No. Each person contributes to one cell. The row and column totals tell us how common the categories are.', 'If the variables were independent, each row would have the same population pattern of column categories. An expected count combines a row total and a column total, divided by the overall total. Expected counts are a model comparison, not extra people.', 'The Pearson chi-squared test compares the observed and expected counts across the whole table. Its approximation can be unreliable when expected cells are small. We use the conservative teaching rule that every expected cell should be at least 5; otherwise this app offers Fisher’s approach. A small p-value indicates evidence of association, not causation.'),
 fisher=c('A small table can have sparse cells even when all calculations are correct. Fisher’s exact test compares your table with other possible tables that have the same row and column totals, under the null hypothesis of no association.', 'For a 2 by 2 table, this avoids the large-count approximation used by the chi-squared test. Observations must still be independent; a before/after table from the same people needs the paired binary route instead.', 'Fisher’s test is not the “non-parametric version of a t-test”. It answers a categorical association question. Zero observed cells are allowed as long as both row and column categories are represented.'),
 fisher_mc=c('For a table larger than 2 by 2, enumerating all relevant tables can be expensive. This option samples 49,999 tables with the same margins under independence, using a fixed seed so the example can be reproduced.', 'The resulting p-value is a Monte Carlo approximation to Fisher’s calculation. It is not an exact numerical p-value. Repeating with another seed could change it slightly, especially near a decision threshold. This teaching app does not silently switch methods if a calculation fails.'),
 mcnemar=c('Imagine asking the same people a Yes/No question before and after. Some stay No, some stay Yes, some change to Yes and some change to No. The two directions of change are the information used by McNemar’s test.', 'The unchanged pairs do not distinguish the two directions. The test asks whether changes towards the event and changes away from it are equally likely. It is a paired analysis; a chi-squared test of independence on the before/after table answers a different question.', 'The approximate version uses a continuity correction. This teaching app offers it when there are at least 25 changed pairs, as a simple conservative guide. The exact version is available regardless of that threshold.'),
 mcnemar_exact=c('Count the people who changed from No to Yes and those who changed from Yes to No. If the population probabilities before and after are equal, the two directions of change should be balanced under the model.', 'The exact version uses a binomial test with probability 0.5 among the changed pairs only. In our example, 12 become Yes and 3 stop being Yes, so the calculation uses 12 out of 15 changers.', 'Keep the overall before/after percentages beside this calculation. The binomial confidence interval concerns the direction among changers, not a confidence interval for the difference in the overall percentages. When nobody changes, there are no discordant pairs for this test.')
 )
}
h_lesson_titles <- c('Start with a question','Understand the study structure','Inspect the data and assumptions','Understand the chosen test','Understand p-values and decisions','Read and report the result','Why adjust for multiple comparisons?')
h_lesson_text <- function(k,i) {
 switch(as.character(i),
 '1'=c('You usually observe one sample, not every person in the population. A difference in this sample could reflect a population difference, sampling variation, or both. Begin by saying what population question you want to answer.',
  switch(k,one='For our fictional sleep study, the question is whether the population mean differs from 7 hours. The null hypothesis is a precise starting statement: the population mean is 7 hours.',paired='For our fictional before/after study, the question is whether people change on average. The no-change statement concerns the population mean of after minus before, which would be 0.',two='For our fictional programme study, we compare different people in two groups. The no-difference statement says the two population means are equal.',many='For our three-programme example, the starting statement says all three population means are equal. The overall alternative is that at least one differs.',binary='For our fictional survey, we compare the population Yes proportion with 50%. This reference should come from the study question, not be chosen because it gives an attractive result.',categorical='For our fictional programme and response table, we ask whether response is associated with programme. Independence means that the population response pattern does not depend on programme.',paired_binary='For our fictional before/after survey, we ask whether the population Yes proportion changes. Compare the two directions of change within people.'),
  'An alternative hypothesis describes the departure you are looking for. A two-sided question allows a difference in either direction. A one-sided question should have a clear justification set before examining the data; do not switch direction after seeing a p-value.'),
 '2'=c('Ask what one row represents. Are different rows different, independent people? Or are there repeated measurements from the same person? A test cannot discover this from the column names.',
  if(k%in%c('paired','paired_binary'))'In this paired route, one row must contain both measurements from the same person or matched pair. Keep the pairing intact. If either value is missing, that whole pair is omitted for this analysis. The remaining pairs should be independent of one another.'else'In this route, each person contributes one independent observation. Families, classes, clinics, repeated visits or matched participants can create dependence that these simple tests do not account for.',
  'Check units, category meanings and missing values. The app reports how many complete observations are used. Removing missing rows is a calculation step; it does not establish that missingness is harmless.'),
 '3'=if(h_numeric(k))c('Begin with the dots and boxplots. Look for recording mistakes, unusually extreme values and differences in spread. Then look at the histograms. A roughly normal shape is reasonably balanced around its centre; small samples may look irregular even when their population is normal.',
  if(k=='paired')'For a paired t-test, inspect the after-minus-before changes. We do not judge normality by combining the two measurement columns or testing their variances against each other.'else if(k%in%c('two','many'))'Inspect the shape within each group. Mixing groups with different means can create a non-normal overall picture even when each group is approximately normal.'else'For a one-sample t-test, inspect the numerical measurements. Severe skew or extreme observations in a small sample need particular care.',
  'A normal Q–Q plot compares the ordered observations with the pattern expected from a normal distribution. Dots roughly following the line support that approximation. Systematic curves or distant end points deserve attention. A boxplot alone cannot establish normality; these visual judgements are guides, not proof.',
  'For positive, right-skewed measurements, a natural log can reduce the influence of large values. Recheck the transformed observations. On this scale the population question concerns geometric means or ratios. If the transformed pattern is still unsuitable, this app returns you to a non-parametric route on the original scale.',
  if(k%in%c('two','many'))'If you choose a mean-based test, inspect the sample variances next. Variance measures spread in squared units; larger variance means more spread. Similar-looking sample variances do not prove population equality. If unsure, choose Welch, which allows unequal variances.'else NULL,
  'A non-parametric test still has assumptions and may answer a different question. Choose a method for the study design and scientific question, rather than trying alternatives until a small p-value appears.')
  else c('Read the observed counts before any percentages or test results. Each cell must count people or complete pairs, not percentages or summary means.',
   if(k=='paired_binary')'Find the off-diagonal cells: people who changed from No to Yes and people who changed from Yes to No. These are the discordant pairs. Unchanged pairs remain important for describing the sample, but do not enter the directional comparison.'else'Expected counts describe what the null model predicts given the sample size or table margins. Small expected counts can make a chi-squared approximation inaccurate. Exact tests do not need that large-count approximation.',
   'Independence and the sampling design still matter. A very large sample or an exact test does not compensate for the wrong study structure.'),
 '5'=c('Suppose the population mean really is 7 hours. Ask 100 imaginary researchers to each collect a fresh sample from that population. Their sample means will differ, and some will look surprisingly far from 7 just by sampling variation.',
  'A p-value compares your result with what could happen under the null hypothesis and the test assumptions. It asks about results this extreme or more extreme; it does not give the probability that the null hypothesis is true, or the probability that the result happened “by chance”.',
  'The significance level is a decision rule chosen beforehand. At 5%, a valid test may reject a true null hypothesis in about 5% of repeated studies. That is a long-run rate, not a guarantee of exactly 5 in any batch of 100.',
  'A non-significant result does not prove no effect. A small study can miss an important effect. A huge study can detect a difference too small to matter. Estimate sizes and uncertainty alongside the p-value.',
  'Try the simulation below. With a true mean of 7, highlighted studies are false positives. Change the true mean to 7.5 or 8: the null is now false, and the highlighted fraction illustrates power. Every run still tests the same null mean of 7.'),
 '6'=c('Report the study groups or paired structure, the number of observations, the observed summaries, the test name and the p-value. When available, include the estimated mean, difference or proportion with its confidence interval.',
  'For a two-sided t-test, a matching confidence interval excludes the null value exactly when the result passes the corresponding significance threshold, apart from rounding. Do not generalise this exact equivalence to every discrete test or mix intervals from different methods.',
  'For rank tests, report descriptive medians and spreads while naming the rank-based comparison correctly. For an overall several-group test, distinguish the overall conclusion from any adjusted pairwise follow-up.',
  'Describe evidence in the context of the study question. Avoid “the null is proven”, “there is no effect” or “p is the probability we are wrong”. Statistical association alone does not establish cause and effect.')
 )
}
h_simulation <- function(n=20,truth=7,seed=2026) {
 set.seed(seed);means<-pvalues<-numeric(100)
 for(i in 1:100){x<-rnorm(n,mean=truth,sd=1.5);means[i]<-mean(x);pvalues[i]<-t.test(x,mu=7)$p.value}
 a<-data.frame(Study=1:100,Mean=means,Decision=ifelse(pvalues<.05,'p < 0.05','p >= 0.05'))
 fig<-ggplot2::ggplot(a,ggplot2::aes(Mean,Study,colour=Decision))+ggplot2::geom_vline(xintercept=7,linetype=2,colour='#526b75')+ggplot2::geom_point(size=2)+ggplot2::scale_colour_manual(values=c('p < 0.05'='#a45179','p >= 0.05'='#087f8c'))+ggplot2::labs(x='One mean from each study (hours)',y='Imaginary study',colour=NULL,title='100 fresh studies, all testing a null mean of 7')+h_theme()
 code<-paste(c('# Sampling experiment: fictional sleep measurements','library(ggplot2)',paste0('set.seed(',seed,')'),paste0('n <- ',n),paste0('true_mean <- ',truth),'sample_means <- p_values <- numeric(100)',
 'for (i in 1:100) {','  sleep <- rnorm(n, mean = true_mean, sd = 1.5)','  sample_means[i] <- mean(sleep)','  p_values[i] <- t.test(sleep, mu = 7)$p.value','}',
 'sum(p_values < 0.05)  # Studies that reject the fixed null mean of 7',
 'simulation <- data.frame(study = 1:100, mean = sample_means, significant = p_values < 0.05)',
 'ggplot(simulation, aes(x = mean, y = study, colour = significant)) +',
 '  geom_point() + geom_vline(xintercept = 7, linetype = 2) + theme_minimal()'),collapse='\n')
 list(plot=fig,reject=sum(pvalues<.05),code=code,table=a)
}

h_multiple_lesson <- function() shiny::tagList(
 shiny::p('Imagine comparing three programmes: A, B and C. There are three pairs: A versus B, A versus C, and B versus C. Each extra test gives sampling variation another opportunity to produce a small p-value, even if all population means are equal.'),
 shiny::p('Think of these three tests as one family of questions. At a 5% family threshold, we aim to keep the chance of at least one false positive in the family at no more than 5%, when the test assumptions hold. Without correction, three independent tests at 5% would give about a 14% chance of at least one false positive. Group comparisons share data, so their exact unadjusted risk is not necessarily 14%.'),
 shiny::h4('Bonferroni: share the allowance across the tests'),
 shiny::p('For three planned comparisons, divide 0.05 by 3: each raw p-value must be below about 0.0167. Equivalently, multiply each raw p-value by 3 (never above 1), then compare the adjusted p-value with 0.05. Use either approach; do not adjust the p-value and divide the threshold again.'),
 shiny::p('Suppose the raw p-values are 0.01, 0.03 and 0.20. Bonferroni gives 0.03, 0.09 and 0.60. Only the first comparison passes the 5% family threshold. The second looked significant alone but does not pass after allowing for all three questions.'),
 shiny::h4('How Holm and Tukey differ'),
 shiny::p('Holm starts with the smallest p-value and uses successively less strict thresholds as it works through the ordered tests. It also controls the family false-positive risk and is at least as powerful as ordinary Bonferroni. For these same three values, Holm gives 0.03, 0.06 and 0.20. Again, only the first comparison passes.'),
 shiny::p('Tukey is designed for all pairwise mean comparisons in an equal-variance ANOVA model. It provides simultaneous confidence intervals as well as adjusted p-values. Welch ANOVA here uses pairwise Welch tests with Holm or Bonferroni; Kruskal–Wallis uses pairwise rank-sum tests with Holm or Bonferroni. These are different follow-up procedures, so the app always names the method.'),
 shiny::p('Adjusted p means a p-value after the stated correction. Compare it with the original family threshold, for example 0.05. Define the family before examining which results look attractive. Correction covers the pairs shown, not every analysis you might try elsewhere. It does not fix biased data, poor design or inappropriate tests.'),
 shiny::p('The plot below shows the same three p-values before and after Bonferroni correction. The dashed line is 0.05. Read how comparison A–C moves from below that line to above it.'),
 shiny::tags$a(href='https://stat.ethz.ch/R-manual/R-patched/library/stats/html/p.adjust.html',target='_blank',rel='noopener','R documentation: p.adjust()'))
h_multiple_plot <- function(){
 d<-data.frame(Comparison=rep(c('A versus B','A versus C','B versus C'),2),P=c(.01,.03,.20,.03,.09,.60),Method=rep(c('Unadjusted','Bonferroni'),each=3))
 ggplot2::ggplot(d,ggplot2::aes(x=Comparison,y=P,colour=Method))+ggplot2::geom_point(position=ggplot2::position_dodge(width=.4),size=3)+ggplot2::geom_hline(yintercept=.05,linetype='dashed')+ggplot2::labs(y='p-value',x=NULL)+h_theme()
}
